"""Service catalog organized in 5 Netflix-style categories."""
from __future__ import annotations
from typing import Any

CATEGORIES = [
    {"id":"operacao","title":"Operação Diária","icon":"🎯",
     "tagline":"Onde você executa o dia a dia","color":"#e50914"},
    {"id":"relacionamento","title":"Relacionamento","icon":"👥",
     "tagline":"Conhecer e cuidar de cada cliente","color":"#3b82f6"},
    {"id":"comercial","title":"Comercial","icon":"💰",
     "tagline":"Funil, previsão e fechamento","color":"#22c55e"},
    {"id":"growth","title":"Crescimento","icon":"📣",
     "tagline":"Captação e nutrição de leads","color":"#f59e0b"},
    {"id":"governanca","title":"Governança","icon":"⚙️",
     "tagline":"Visão de cima e controle","color":"#a855f7"},
]

def _s(sid, cat_id, cat_label, title, tagline, summary, desc, inputs, steps, outcome, bench, integ):
    """summary=objetivo | desc=resumo geral | inputs=dados | steps=como usar | outcome=resultado esperado."""
    return {
        "id": sid,
        "category_id": cat_id,
        "category": cat_label,
        "title": title,
        "tagline": tagline,
        "summary": summary,
        "description": desc,
        "inputs": inputs,
        "steps": steps,
        "outcome": outcome,
        "benchmark": bench,
        "integrations": integ,
        "ready_to_use": True,
        "objetivo": summary,
        "resumo_geral": desc,
        "resultado_esperado": outcome,
        "dados_input": inputs,
        "como_usar": steps,
    }


def service_guide_payload(service: dict[str, Any]) -> dict[str, Any]:
    """Campos padronizados do guia (4 blocos + metadados)."""
    return {
        "id": service["id"],
        "title": service["title"],
        "category": service["category"],
        "tagline": service.get("tagline", ""),
        "objetivo": service.get("objetivo") or service.get("tagline", ""),
        "resumo_geral": service.get("resumo_geral") or service.get("description", ""),
        "resultado_esperado": service.get("resultado_esperado") or service.get("outcome", ""),
        "dados_input": service.get("dados_input") or service.get("inputs", []),
        "como_usar": service.get("como_usar") or service.get("steps", []),
    }

SERVICE_CATALOG = [
    _s("ticketing-sla","operacao","Operação Diária","Central de Atendimento",
       "Fila operacional com SLA, prioridade e roteamento.",
       "Entra demanda do cliente, sai resposta no prazo.",
       "Centraliza chamados de qualquer canal em fila unica com owner, SLA e historico.",
       ["Cliente cadastrado","Assunto","Prioridade","Categoria","Owner"],
       ["Abrir Atendimento","Novo ticket","Atribuir owner","Acompanhar","Resolver e CSAT"],
       "Visibilidade total da fila, SLA monitorado.",
       "Salesforce Service Cloud, Zendesk, Freshdesk, RD Conversas.",
       ["channel-intake","customer-360","templates"]),
    _s("channel-intake","operacao","Operação Diária","Entrada Multicanal",
       "WhatsApp, Email e Formularios viram tickets automaticos.",
       "Toda mensagem por canal externo entra como ticket.",
       "Recebe entradas e cria ticket vinculado ao cliente certo.",
       ["Mensagem recebida","Identificacao","Canal"],
       ["Abrir Canais","Selecionar aba","Colar mensagem","Validar","Confirmar"],
       "Ticket criado, cliente cadastrado se novo.",
       "RD Conversas, Twilio Flex, HubSpot Inbox.",
       ["ticketing-sla","customer-360"]),
    _s("tasks-cadences","operacao","Operação Diária","Tarefas e Cadências",
       "Sequências automáticas de follow-up.",
       "Cliente recebe boas-vindas D+0, follow-up D+1, check-in D+7.",
       "Cadências programadas de toques com intervalos.",
       ["Cliente alvo","Cadência","Responsável"],
       ["Abrir Cadências","Selecionar","Inscrever","Receber lembretes","Marcar feito"],
       "Sem cliente esquecido, sem follow-up perdido.",
       "Outreach, Salesloft, Reev, Apollo.",
       ["templates","pipeline","customer-360"]),
    _s("customer-360","relacionamento","Relacionamento","Cliente 360",
       "Ficha unica com tudo que aconteceu com a conta.",
       "Tickets, deals, interacoes e health em uma tela.",
       "Visao consolidada com perfil, timeline, tickets, oportunidades, LTV.",
       ["Conta cadastrada","Interacoes registradas"],
       ["Abrir Clientes 360","Filtrar","Selecionar","Revisar timeline"],
       "Contexto completo em segundos.",
       "Salesforce Customer 360, HubSpot, Zoho, Pipedrive.",
       ["timeline","health-score","ticketing-sla","pipeline"]),
    _s("timeline","relacionamento","Relacionamento","Histórico 360",
       "Histórico cronológico de toda interação.",
       "Tudo do cliente em ordem cronológica.",
       "Cada evento entra com data, canal, responsável e resumo.",
       ["Eventos automáticos","Eventos manuais opcionais"],
       ["Abrir Clientes 360","Selecionar conta","Rolar histórico"],
       "Memória preservada.",
       "HubSpot, linha do tempo Salesforce.",
       ["customer-360"]),
    _s("health-score","relacionamento","Relacionamento","Saúde da Conta e Risco de Cancelamento",
       "Identifica contas em risco automaticamente.",
       "Nota 0-100 baseada em sinais de uso e relacionamento.",
       "Combina interação, ticket crítico, CSAT, funil, responsável e compra.",
       ["Calculado dos dados existentes"],
       ["Abrir Saúde da Conta","Recalcular","Filtrar risco","Acionar ação"],
       "Lista priorizada com acoes claras.",
       "Gainsight, ChurnZero, Totango.",
       ["customer-360","tasks-cadences","ai-insights"]),
    _s("templates","relacionamento","Relacionamento","Modelos de Mensagem",
       "Mensagens padronizadas com variáveis.",
       "10 modelos prontos com variáveis automáticas.",
       "Biblioteca para boas-vindas, follow-up, atendimento e retenção.",
       ["Cliente alvo","Modelo selecionado"],
       ["Abrir Modelos","Filtrar","Selecionar cliente","Copiar"],
       "Tempo de resposta reduzido.",
       "Intercom Saved Replies, Zendesk Macros.",
       ["tasks-cadences","ticketing-sla","channel-intake"]),
    _s("pipeline","comercial","Comercial","Funil Comercial",
       "Funil visual com 4 etapas.",
       "Oportunidades organizadas por etapa.",
       "Visualiza negócios em colunas com cliente, valor e probabilidade.",
       ["Cliente cadastrado","Nome, valor, prob., etapa"],
       ["Abrir Funil Comercial","Nova oportunidade","Acompanhar"],
       "Previsão confiável, gargalos visíveis.",
       "Pipedrive, RD CRM, HubSpot, Ploomes.",
       ["forecast","customer-360","tasks-cadences"]),
    _s("forecast","comercial","Comercial","Previsão de Receita",
       "Previsão ponderada por probabilidade.",
       "Quanto vai entrar este mês? Com qual confiança?",
       "Receita esperada combinando valor × probabilidade.",
       ["Funil com oportunidades"],
       ["Abrir Previsão","Selecionar período","Analisar"],
       "Previsão confiável.",
       "Salesforce, HubSpot, Clari.",
       ["pipeline","productivity"]),
    _s("productivity","comercial","Comercial","Produtividade do Time",
       "Performance individual e coletiva.",
       "Quem fechou quanto e quem resolveu mais.",
       "Relatorio por owner com tickets, deals, win rate, receita.",
       ["Periodo de analise"],
       ["Abrir Produtividade","Selecionar periodo","Comparar"],
       "Base para coaching.",
       "Salesforce Reports, Geckoboard, Domo.",
       ["pipeline","ticketing-sla","forecast"]),
    _s("marketing-campaigns","growth","Crescimento","Campanhas de Marketing",
       "Email, WhatsApp, eventos e ads com ROI.",
       "Cadastre, registre e veja conversao.",
       "Hub de campanhas com leads, qualificados, conversao, receita.",
       ["Nome, canal, leads, qualificados"],
       ["Abrir Marketing","Nova campanha","Comparar"],
       "Decisao de orcamento por ROI.",
       "RD Station, HubSpot, Marketo.",
       ["lead-scoring","customer-360"]),
    _s("lead-scoring","growth","Crescimento","Qualificação de Leads",
       "Pontua cada lead de 0 a 100.",
       "Vendas prioriza faixa A.",
       "Avalia conta com regras configuráveis e gera faixas A/B/C/D.",
       ["10 regras padrão editáveis"],
       ["Abrir Qualificação","Recalcular","Trabalhar por faixa"],
       "Conversão maior, foco em lead quente.",
       "RD Station, HubSpot, Pardot.",
       ["marketing-campaigns","customer-360","pipeline"]),
    _s("segmentation","growth","Crescimento","Segmentação Inteligente",
       "Grupos dinâmicos por atributos.",
       "Crie listas e exporte para campanhas.",
       "Filtra base por combinações de atributos.",
       ["Filtros (mercado, status, responsável)"],
       ["Abrir Segmentação","Aplicar filtros","Exportar"],
       "Comunicacao mais relevante.",
       "RD Station Segmentos, HubSpot Lists.",
       ["marketing-campaigns","tasks-cadences"]),
    _s("executive-view","governanca","Governança","Visão Executiva",
       "KPIs do negócio em uma tela.",
       "CSAT, SLA, receita e funil.",
       "Painel com KPIs principais.",
       ["Operação gera os números"],
       ["Abrir Visão Executiva","Filtrar","Revisar"],
       "Decisao por dado.",
       "Salesforce Lightning, Tableau, Power BI.",
       ["pipeline","ticketing-sla","forecast","health-score"]),
    _s("ai-insights","governanca","Governança","Insights com IA",
       "Resumos, sugestões e classificação automática.",
       "Sistema lê os dados e diz o que fazer.",
       "Resumo, próxima ação e classificação de ticket.",
       ["Dados existentes"],
       ["Abrir Insights com IA","Selecionar","Ler insight"],
       "Equipe ganha tempo e foco.",
       "Salesforce Einstein, HubSpot ChatSpot, Zendesk AI.",
       ["customer-360","ticketing-sla","health-score"]),
    _s("rbac-admin","governanca","Governança","Administração e Permissões",
       "Usuários, perfis, permissões e auditoria.",
       "Quem pode fazer o que.",
       "Painel com usuários, matriz de permissões e trilha de auditoria.",
       ["Usuários","Ações padrão"],
       ["Abrir Administração","Editar matriz","Auditar"],
       "Compliance auditavel.",
       "Salesforce Profiles, Auth0, Okta.",
       []),
    _s("benchmark","governanca","Governança","Comparativo de Mercado",
       "Compara seu CRM com líderes.",
       "O que cada concorrente faz melhor.",
       "Tabela comparativa Brasil e EUA.",
       ["Conhecimento estruturado"],
       ["Abrir Comparativo","Revisar","Conferir abas"],
       "Direcao clara para evoluir.",
       "G2, Capterra, Forrester, Gartner.",
       []),
]

def get_services_by_category(cid):
    return [s for s in SERVICE_CATALOG if s["category_id"] == cid]

def get_service_by_id(sid):
    for s in SERVICE_CATALOG:
        if s["id"] == sid: return s
    return None

SERVICE_TO_SECTION = {
    "ticketing-sla": "Atendimento",
    "channel-intake": "Canais",
    "tasks-cadences": "Cadências",
    "customer-360": "Clientes 360",
    "timeline": "Clientes 360",
    "health-score": "Saúde da Conta",
    "templates": "Modelos de Mensagem",
    "pipeline": "Funil Comercial",
    "forecast": "Previsão de Receita",
    "productivity": "Produtividade",
    "marketing-campaigns": "Marketing",
    "lead-scoring": "Qualificação de Leads",
    "segmentation": "Segmentação",
    "executive-view": "Visão Executiva",
    "ai-insights": "Insights com IA",
    "rbac-admin": "Administração",
    "benchmark": "Comparativo de Mercado",
}

def resolve_service_section(sid):
    return SERVICE_TO_SECTION.get(sid, "Visão Executiva")
