"""Catálogo de serviços guiados para a vitrine do CRM."""

from __future__ import annotations

SERVICE_CATALOG = [
    {
        "id": "customer-360",
        "title": "Cliente 360",
        "category": "Relacionamento",
        "tagline": "Histórico unificado, saúde da conta e próxima ação.",
        "description": "Centraliza dados da conta, timeline de interações, owner, saúde, tickets e oportunidades ligadas ao cliente.",
        "outcome": "Você consegue entender rapidamente o contexto completo do cliente antes de agir.",
        "inputs": [
            "Nome da conta ou cliente existente",
            "Segmento e mercado",
            "Owner responsável",
            "Canal preferencial",
            "Próxima ação recomendada",
        ],
        "steps": [
            "Abra a área Clientes 360 ou use esta vitrine para revisar o objetivo do serviço.",
            "Confirme se a conta já existe ou se precisa ser criada.",
            "Preencha owner, segmento, canal e próxima ação.",
            "Use a timeline para registrar cada interação importante.",
            "Revise tickets e oportunidades conectadas antes de falar com o cliente.",
        ],
        "cta": "Resultado esperado: visão única do cliente para atendimento, vendas e expansão.",
    },
    {
        "id": "ticketing-sla",
        "title": "Tickets e SLA",
        "category": "Atendimento",
        "tagline": "Criação de tickets com prioridade, categoria e leitura de prazo.",
        "description": "Registra chamados manuais ou oriundos de canais, organizando fila operacional, prioridade e risco de SLA.",
        "outcome": "A equipe sabe exatamente o que atender primeiro e quais casos exigem escalonamento.",
        "inputs": [
            "Cliente vinculado",
            "Assunto do caso",
            "Categoria do ticket",
            "Prioridade",
            "Canal de origem",
            "Resumo do atendimento",
        ],
        "steps": [
            "Selecione o cliente correto ou crie a conta se ela ainda não existir.",
            "Defina assunto, categoria, prioridade e canal de entrada.",
            "Escreva um resumo claro com contexto suficiente para continuidade.",
            "Valide owner e SLA alvo antes de salvar.",
            "Após criar, acompanhe o status na fila de atendimento.",
        ],
        "cta": "Resultado esperado: ticket rastreável, com contexto, dono e prioridade definidos.",
    },
    {
        "id": "channel-intake",
        "title": "Intake Multicanal",
        "category": "Operação",
        "tagline": "WhatsApp, Email e Formulário em uma única entrada operacional.",
        "description": "Padroniza a captura de mensagens recebidas e transforma a demanda em ticket com cliente vinculado.",
        "outcome": "Nenhum contato se perde e toda solicitação já entra pronta para triagem.",
        "inputs": [
            "Canal de origem",
            "Cliente existente ou novo cliente",
            "Assunto",
            "Responsável",
            "Prioridade",
            "Cidade e país",
            "Mensagem recebida ou arquivo importado",
        ],
        "steps": [
            "Escolha a aba do canal correspondente.",
            "Informe se a demanda pertence a um cliente existente ou a um novo contato.",
            "Preencha assunto, owner, prioridade e dados básicos do contato.",
            "Cole a mensagem ou importe um arquivo com o conteúdo recebido.",
            "Registre a entrada para gerar o cliente e o ticket vinculados.",
        ],
        "cta": "Resultado esperado: entrada registrada com histórico, cliente e ticket conectados.",
    },
    {
        "id": "pipeline",
        "title": "Pipeline Comercial",
        "category": "Vendas",
        "tagline": "Funil visual com etapa, valor, probabilidade e previsão de fechamento.",
        "description": "Organiza oportunidades por estágio comercial e conecta cada deal ao cliente certo.",
        "outcome": "O time comercial enxerga valor em aberto, ganho esperado e próximos movimentos do funil.",
        "inputs": [
            "Cliente da oportunidade",
            "Nome da oportunidade",
            "Etapa do funil",
            "Valor estimado",
            "Probabilidade",
            "Owner comercial",
            "Origem",
            "Data prevista de fechamento",
        ],
        "steps": [
            "Selecione a conta correta antes de abrir a oportunidade.",
            "Defina nome, etapa e valor estimado do negócio.",
            "Informe a probabilidade realista e o owner responsável.",
            "Registre a origem do deal e a data de fechamento prevista.",
            "Acompanhe a oportunidade no funil e ajuste estágio conforme evolução.",
        ],
        "cta": "Resultado esperado: funil confiável para previsão e gestão de receita.",
    },
    {
        "id": "marketing-campaigns",
        "title": "Campanhas de Marketing",
        "category": "Marketing",
        "tagline": "Leads, qualificação, conversão e receita em uma leitura única.",
        "description": "Permite cadastrar campanhas e acompanhar impacto por canal com foco em contribuição para receita.",
        "outcome": "A operação identifica quais campanhas merecem escala e quais precisam de correção.",
        "inputs": [
            "Nome da campanha",
            "Canal",
            "Leads gerados",
            "Leads qualificados",
            "Taxa de conversão",
            "Receita atribuída",
        ],
        "steps": [
            "Cadastre a campanha com nome e canal corretos.",
            "Informe volume de leads e quantidade qualificada.",
            "Preencha taxa de conversão e receita atribuída.",
            "Compare os canais no painel de conversão.",
            "Use a leitura de negócio para decidir reforço, pausa ou otimização.",
        ],
        "cta": "Resultado esperado: marketing conectado ao impacto comercial real.",
    },
    {
        "id": "rbac-admin",
        "title": "Admin e RBAC",
        "category": "Governança",
        "tagline": "Controle de perfis, permissões e trilha de auditoria.",
        "description": "Concentra governança operacional, usuários, regras de acesso e histórico auditável de mudanças.",
        "outcome": "A administração controla quem pode fazer o quê e mantém rastreabilidade das alterações.",
        "inputs": [
            "Role a ser editado",
            "Ações permitidas",
            "Usuários ativos",
            "Eventos auditados",
        ],
        "steps": [
            "Abra a área Admin com um usuário com permissão adequada.",
            "Selecione o role que deseja revisar.",
            "Marque ou desmarque as ações permitidas na matriz RBAC.",
            "Salve as alterações para persistir no banco.",
            "Revise a trilha de auditoria para confirmar o before/after das mudanças.",
        ],
        "cta": "Resultado esperado: segurança operacional com governança e auditoria.",
    },
]